GET http://localhost:3000/token
x-api-key: 53Hz8iiGhDBHOGCH7kB1XwsohBtZjQ9P


###

GET http://localhost:3000/protected
Authorization: Bearer <token>

###

GET http://localhost:3000/admin
Authorization: Bearer <token>